### ISSUE TITLE
Use artipie parent pom

### ISSUE THREAD

**Issue by g4s8** [artipie/files-adapter#1]
Let's use [parent pom](https://github.com/artipie/ppom):
```xml
<parent>
  <groupId>com.artipie</groupId>
  <artifactId>ppom</artifactId>
  <version>0.2.1</version>
</parent>
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I'm not managing this repo, remove the [webhook](https://github.com/artipie/files-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/files-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by Sammers21** [comment]
@g4s8 , i m working on it

**Comment by g4s8** [comment]
@0crat assign @Sammers21

**Comment by 0crat** [comment]
I'm not managing `artipie/files-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
Job `gh:artipie/files-adapter#1` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
