### ISSUE TITLE
Update to latest HTTP

### ISSUE THREAD

**Issue by g4s8** [artipie/files-adapter#10]
Update HTTP version, use routing classes from http module

**Comment by 0crat** [comment]
The job [#10](https://github.com/artipie/files-adapter/issues/10) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f68f39e4-584c-44ef-aa09-875b095db155); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.2.1`

**Comment by g4s8** [comment]
Done
