### ISSUE TITLE
Return metadata headers

### ISSUE THREAD

**Issue by g4s8** [artipie/files-adapter#107]
Parse metadata of requested item if URL parameter is `meta=true`, and return it as headers with prefix `X-Artipie-{meta-key}: {meta-value}`, e.g.:
```http
200 OK HTTP/1.1
X-Artipie-MD5: md5sum
X-Artipie-CreatedAt: timestamp
X-Artipie-Size: 123
```

Return these headers for `GET` and `HEAD` requests of concrete items (not for listing).

Blocks: #106

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#110](https://github.com/artipie/files-adapter/issues/110) is still not solved.
