### ISSUE TITLE
Add authentication to files adapter

### ISSUE THREAD

**Issue by g4s8** [artipie/files-adapter#13]
Add basic authentication to files adapter and authorize users for upload and download.

**Comment by 0crat** [comment]
The job [#13](https://github.com/artipie/files-adapter/issues/13) assigned to @ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/9f7a711a-4e0f-4046-8eec-d9ed9c27b6a0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat wait #14 PR to be merged

**Comment by 0crat** [comment]
> @0crat wait #14 PR to be merged ([here](https://github.com/artipie/files-adapter/issues/13#issuecomment-618378715))

@g4s8 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c08ec908-6891-4027-9aad-79415e47ffee, thread: PQ-CT2E6TK9B
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.in.impediments.add_waiting_label
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.io.IOException: failed after 4 attempts
com.jcabi.http.wire.RetryWire[95] java.io.IOException: failed after 4 attempts
```

[0.53.11](https://github.com/zerocracy/farm): CID: [56b90722-1846-4af6-b033-84985effa1db](https://www.0crat.com/footprint/CT2E6TK9B/56b90722-1846-4af6-b033-84985effa1db), Type: "Impediment was registered"

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by g4s8** [comment]
@rultor release, tag=`0.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.3`
