### ISSUE TITLE
Delete API

### ISSUE THREAD

**Issue by g4s8** [artipie/files-adapter#15]
Implement delete API, it should process `DELETE` HTTP method and delete resources by key provided. E.g.:
```httml
DELETE /file1 HTTP/1.1
```
should remove object in storage with key `file1`.

**Comment by 0crat** [comment]
The job [#15](https://github.com/artipie/files-adapter/issues/15) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/7f60dbaa-83af-48c2-9c60-9c698625c561); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@rultor refuse

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/files-adapter/issues/15#issuecomment-627792436))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#15](https://github.com/artipie/files-adapter/issues/15), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#15](https://github.com/artipie/files-adapter/issues/15) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/97345886-386e-4681-9d36-a6cadb27765e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for artipie/http#148

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status  ([here](https://github.com/artipie/files-adapter/issues/15#issuecomment-634601334))

@victornoel This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#15](https://github.com/artipie/files-adapter/issues/15) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Ffiles-adapter%2315%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@g4s8 can you re-assign me here too?

**Comment by g4s8** [comment]
@0crat assign @victornoel

**Comment by 0crat** [comment]
> @0crat assign @victornoel  ([here](https://github.com/artipie/files-adapter/issues/15#issuecomment-635168321))

@g4s8 The job [#15](https://github.com/artipie/files-adapter/issues/15) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/cfff3cf6-b051-43c5-ab44-b4e0751f1ebb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for artipie/http#148

**Comment by victornoel** [comment]
@g4s8 I think this can be closed now :)

**Comment by g4s8** [comment]
@victornoel yes, thanks

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment
