### ISSUE TITLE
Headers and body should not be sent to remote by proxy

### ISSUE THREAD

**Issue by olegmoz** [artipie/files-adapter#40]
Files proxy now sends received request as whole to remote. Only request line is part of lines protocol and passing all headers is dangerous

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olegmoz** [comment]
@rultor release, tag=`0.6.1`

**Comment by 0crat** [comment]
Job `gh:artipie/files-adapter#40` is not assigned, can't get performer
